name: Gradle Build
on: {push: {tags: null}}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: vaccovecrana/gitflow-oss-java-slim@1.8.3
        with:
          orgConfig: https://raw.githubusercontent.com/rqlite/rqlite-jdbc/refs/heads/org-config/org-config.json
        env:
          CENTRAL_PORTAL_USERNAME: ${{secrets.CENTRAL_PORTAL_USERNAME}}
          CENTRAL_PORTAL_PASSWORD: ${{secrets.CENTRAL_PORTAL_PASSWORD}}
          MAVEN_SIGNING_KEY: ${{secrets.MAVEN_SIGNING_KEY}}